name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: .

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: |
          npm install
        working-directory: .


      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --trace
        working-directory: .
        env:
          JEKYLL_ENV: production


      - name: Build Tailwind CSS
        run: |
          npm run build
        working-directory: .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

